services:
  - type: web
    name: tiffinwala
    env: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production